language: python

cache: pip

python:
    - "2.7"
    - "3.6"

install:
    - pip install pycodestyle pytest

script:
    - pycodestyle --exclude=operational_task.py
    - python setup.py test

notifications:
    email: false
