language: python

python:
    - "2.7"
    - "3.6"

install:
    - pip install pycodestyle pytest

script:
    - pycodestyle --exclude=operational_task.py
    - pytest

notifications:
    email: false
